export {default as Home} from './pages/Home/Home'
export {default as Login} from './pages/Login/Login'
export {default as SignUp} from './pages/SignUp/SignUp'
export {default as Tasks} from './pages/Tasks/Tasks'
export {default as Navbar} from './Navbar/Navbar'